### ISSUE TITLE
部署和使用本项目的主要障碍是什么？

### ISSUE THREAD

**Issue by LittleShrimp1987** [AutohomeCorp/frostmourne#1]
1. 部署搭建比较困难

2. 功能难用

3. 场景不适合

4. 没有障碍 

这里列出几个我能想到的主要障碍，如果有其他问题，欢迎补充

**Comment by xyzj91** [comment]
部署搭建比较困难

**Comment by LittleShrimp1987** [comment]
> 部署搭建比较困难

收到，愿意的话，可以加入qq群1082617505，我们会在群里提供支持。

**Comment by hbzhu** [comment]
我希望能有helm部署方式，我需要运行在kubernetes上

**Comment by LittleShrimp1987** [comment]
> 我希望能有helm部署方式，我需要运行在kubernetes上

收到，我研究研究

**Comment by lvelvis** [comment]
建议加入docker-compose管理启动，不然部署太繁琐了

**Comment by LittleShrimp1987** [comment]
> 建议加入docker-compose管理启动，不然部署太繁琐了

在quick-start里是有docker-compose的

**Comment by lvelvis** [comment]
tks

**Comment by abccbaandy** [comment]
請問如果要自己從source打包要怎麼弄？
quick-start裡的都是打包好的docker image.

doc/docker底下的Dockerfile似乎跟專案目錄路徑對不上

**Comment by LittleShrimp1987** [comment]
> 請問如果要自己從source打包要怎麼弄？ quick-start裡的都是打包好的docker image.
> 
> doc/docker底下的Dockerfile似乎跟專案目錄路徑對不上

readme已经更新说明
