### ISSUE TITLE
当数据源为多层json时，[数据查询]中部分字段会显示为undefined

### ISSUE THREAD

**Issue by fox2zz** [AutohomeCorp/frostmourne#11]
#### [简述你的问题]
当数据为多层json时，[数据查询]中部分字段会显示为undefined

#### 使用版本
[请提供你使用的frostmourne版本]
master:6452c52

#### 具体表现[截图可能会更好些,最好能截全]
数据查询——>当数据源为多层json格式
例如：
```
{
    "@timestamp": "2020-07-08T12:40:04.712Z",
    "architecture": "x86_64",
    "os": {
        "kernel": "6.1.7601.24545 (win7sp1_ldr_escrow.200102-1707)",
        "build": "7601.24544",
        "platform": "windows",
        "version": "6.1",
        "family": "windows",
        "name": "Windows Server 2008 R2 Enterprise"
    }
}
```
其中的 `os` 字段在表格中会显示为 undefined，数据展开后显示正常
|@timestamp|architecture|os|
| ---- | ---- | ---- |
|2020-07-08T12:40:04.712Z|x86_64|undefined|

[注:] 完成后请关闭 issue

**Comment by LittleShrimp1987** [comment]
问题已经修复
