### ISSUE TITLE
当 [数据名] 未填写 [说明] 时，监控编辑中数据源选择显示为空白(可选取)

### ISSUE THREAD

**Issue by fox2zz** [AutohomeCorp/frostmourne#12]
#### [简述你的问题]
当 [数据名] 未填写 [说明] 时，监控编辑中数据源选择显示为空白(可选取)

#### 使用版本
[请提供你使用的frostmourne版本]
master:6452c52

#### 具体表现[截图可能会更好些,最好能截全]

数据名
|ID|名称|说明|
| ---- | ---- | ---- |
|1|dev|dev_env|
|2|ops||
|3|prod||

监控编辑——>数据配置——>数据，下拉框显示为
- dev_env
- 空白
- 空白

#### 其他
可以考虑下拉框显示 [数据名] 中的 [名称]，鼠标悬停显示 [说明]

[注:] 完成后请关闭 issue

**Comment by LittleShrimp1987** [comment]
数据名保存form表单已经增加验证
