### ISSUE TITLE
k8s deployment 部署服务启动失败

### ISSUE THREAD

**Issue by zimu312500** [AutohomeCorp/frostmourne#120]
deployment中提供的镜像 registry.cn-hangzhou.aliyuncs.com/kechangqing/frostmourne:0.9.1启动失败，报错日志如下：

[root@master1 frost]# kfr logs frostmourne-monitor-766858b7ff-jlr68
frostmourne-monitor
Archive:  /opt/frostmourne/frostmourne-monitor.zip
   creating: scripts/
  inflating: scripts/shutdown.sh
  inflating: scripts/startup.sh
  inflating: application.properties
  inflating: env
  inflating: frostmourne-monitor-0.9.1-RELEASE.jar
LOG_DIR: /opt/frostmourne/frostmourne-monitor/scripts/../logs
PID_FOLDER: /opt/frostmourne/frostmourne-monitor/scripts/../pid
Mon Oct 10 11:52:55 UTC 2022 ==== Starting ==== 
Application is running as root (UID 0). This is considered insecure.
Unable to find Java
Mon Oct 10 11:52:55 UTC 2022 Failed to start frostmourne-monitor.jar, return code: 1

**Comment by LittleShrimp1987** [comment]
已经更新docker-compose.yaml文件，使用最新版本。

**Comment by zimu312500** [comment]
docker-compose.yaml中的镜像可以正常启动了，给力。不过我使用的是这个deployment进行的部署，这里面的镜像可以同步更新下。
(https://github.com/AutohomeCorp/frostmourne/tree/master/doc/docker/k8s)/frostmourne-monitor-deployment.yaml

**Comment by LittleShrimp1987** [comment]
好 我更新下
