### ISSUE TITLE
使用数据查询时日志报错

### ISSUE THREAD

**Issue by FengZh61** [AutohomeCorp/frostmourne#126]
![image](https://user-images.githubusercontent.com/98309003/201565981-72fff61c-b49b-4972-94e4-055568823ed2.png)

1，数据名配置，索引前缀，我认为应该是模糊匹配，但是在查询数据时是完全匹配，日志中报没有这个index，我在所以后面加上*，数据查询可以查询出结果，但是日志有WARN告警，不知道是否正常。

**Comment by LittleShrimp1987** [comment]
warn日志没影响，但是有条error这个有影响 你自己看下

**Comment by FengZh61** [comment]
> warn日志没影响，但是有条error这个有影响 你自己看下

ERROR是配置数据名的时候索引前缀的问题，我理解填写graylog  他应该去查的是graylog开头的所有index，但实际上他只去查graylog了。

**Comment by LittleShrimp1987** [comment]
要加*
