### ISSUE TITLE
数值告警能支持统计计算

### ISSUE THREAD

**Issue by wajika** [AutohomeCorp/frostmourne#13]
比如说 统计5分钟内的CPU使用率，一直达到90%，那么就推送一个告警

**Comment by LittleShrimp1987** [comment]
可以监控cpu最近5分钟的平均值，规则设置为大于90%报警，可以满足要求你的要求吗？

**Comment by LittleShrimp1987** [comment]
现在数值判断的阈值框只能输入整数，后面会改成可以输入小数

**Comment by LittleShrimp1987** [comment]
现在已经支持的统计类型有：count,min,max,avg,sum

**Comment by LittleShrimp1987** [comment]
而且es统计监控只要能写rest api计算出来，都可以用HTTP监控来解决，具体请参考文档：https://github.com/AutohomeCorp/frostmourne/blob/master/doc/wiki/http-alarm.md
