### ISSUE TITLE
0.9.1 frostmourne使用问题记录

### ISSUE THREAD

**Issue by wangteng0906** [AutohomeCorp/frostmourne#132]
1、使用terms分桶配置时发现统计的key=value与采集的日志不一致。
     exceptionType中的value要是存在（空格，逗号，等于号，冒号等）就会发生值被分割情况。
![image](https://user-images.githubusercontent.com/72957138/207755684-9e76e97b-68e1-464f-9a4d-bcbce07bf5f8.png)
![image](https://user-images.githubusercontent.com/72957138/207755967-e61a0faf-2ce2-4535-9159-0860c9fb4865.png)
![image](https://user-images.githubusercontent.com/72957138/207756141-849b4721-9621-4f6d-92d6-c65643346e0d.png)
![image](https://user-images.githubusercontent.com/72957138/207756200-891b515e-ef03-42c0-90b9-a7712d199ee0.png)
2、terms分桶配置目前也不支持多个字段聚合，只能是单个字段实现，希望和elastalert对齐配置（elastalert支持多个字段聚合）。
3、触发告警获取到的内容往往是最近一条异常信息，即使做了分桶，告警信息也会最近一条异常信息，无法将分桶配置的异常类型全部告警出来。这对线上业务异常告警很不友好，无法及时直观发现到底触发了哪些异常
![image](https://user-images.githubusercontent.com/72957138/207757473-a4777b7a-7197-4102-aabb-808353b0c975.png)

**Comment by LittleShrimp1987** [comment]
es的特性和项目无关
