### ISSUE TITLE
mysql 数据可以做监控吗

### ISSUE THREAD

**Issue by wuzhixaun** [AutohomeCorp/frostmourne#137]
mysql 数据可以做监控吗，就是监控这个订单的状态等等的变化，目前为什么数据吗的时候需要填时间字段，个人感觉好奇怪

**Comment by LittleShrimp1987** [comment]
可以做mysql数据监控，时间字段用于数值类型规则监控，没有可以随便填一个，不过数值比较规则回报错，可以用表达式规则，详细使用说明看文档
