### ISSUE TITLE
怎么将报警信息发送到仅提供企微群机器人 webhook 地址的群里

### ISSUE THREAD

**Issue by wangchaoforever** [AutohomeCorp/frostmourne#141]
如果不知道企微的下面三个配置（your.wechat.corpid=, your.wechat.agentid=, your.wechat.secret=），那可以直接将告警信息发送到企微群机器人的webhook地址吗？具体该如何操作？

**Comment by LittleShrimp1987** [comment]
可以，搜一下企业微信机器人使用方法的文档

**Comment by wangchaoforever** [comment]
是需要自己写个api解析下 frostmourne 发过来的告警消息，然后再将消息发送到目标机器人吧？

**Comment by LittleShrimp1987** [comment]
微信机器人可以直接把机器人的webhook填上就行了

**Comment by wangchaoforever** [comment]
可能我之前测试的有问题，现在已确认可以直接发送到机器人的 webhook。
