### ISSUE TITLE
钉钉报警出错  error when send ding robot message

### ISSUE THREAD

**Issue by angelo-she** [AutohomeCorp/frostmourne#145]
![image](https://github.com/AutohomeCorp/frostmourne/assets/24379793/e016571a-924f-41c0-aac7-186041afc67c)
<img width="600" alt="image" src="https://github.com/AutohomeCorp/frostmourne/assets/24379793/a8cc4097-b7b8-4821-a985-8e37cdde0979">

**Comment by angelo-she** [comment]
已解决，谢谢！

**Comment by chuqiao8250** [comment]
怎么解决的？我也遇到同样问题

**Comment by uuqwe** [comment]
我也遇到同样的问题，在容器部署向钉钉发送告警失败，虚拟机部署可以成功发送告警
