### ISSUE TITLE
最新版本cron不生效

### ISSUE THREAD

**Issue by XDongo** [AutohomeCorp/frostmourne#146]
如题，部署了1.0版本，添加了监控，但是cron不生效，除了我手动执行有记录外，没有看到自动执行的记录。实际测试 ，确实没有执行
![image](https://github.com/AutohomeCorp/frostmourne/assets/38721169/ecc0cc68-bce6-43c2-b082-6d410a316ee2)

**Comment by deasyful** [comment]
你好， 请问这个问题解决了吗
