### ISSUE TITLE
提两个小建议

### ISSUE THREAD

**Issue by wajika** [AutohomeCorp/frostmourne#15]
1、如果事件发生的时间是21点到早上6点，非紧急告警可以只做记录，而非直接推送。
2、获取到告警消息后 支持告警的分组处理，比如 获取到service.name，发给相关的负责人

**Comment by wajika** [comment]
对于不同的服务需要使用同一个告警规则的情况，是否应该拆分用户和组为一个表，告警规则为一个表，然后只要输入service.name，去关联组编号和规则编号。

**Comment by wajika** [comment]
比如说http404 应该关联上所有前端服务，如果前端有50个，那就需要写50次规则，效率太低。

**Comment by LittleShrimp1987** [comment]
我在考虑做一个批量创建监控的功能，应该能解决你的部分问题

**Comment by wajika** [comment]
![image](https://user-images.githubusercontent.com/17058349/88516857-89580780-d020-11ea-837a-c81b500354f9.png)

功能增强性建议（每周统计报表）
我们计划后续统计某个值，如果值低于X，那么会推送告警（这个你们已经实现），有没有考虑设计一个周榜的形式，专门推送一些本周之内的service.name top信息。 比如说某服务一周之内一直处于高负载。

**Comment by LittleShrimp1987** [comment]
周榜这种属于统计需求，目前项目只专注于监控；不过如果你有一个指标能表示服务一周之内一直处于高负载，你可以监控这个指标的数值来达到监控的目的。

另外，最好不要在一个issue，提多个问题，不然这个issue永远无法close

**Comment by LittleShrimp1987** [comment]
> 比如说http404 应该关联上所有前端服务，如果前端有50个，那就需要写50次规则，效率太低。

增加监控模板功能：可以创建多个变量，变量名用于填写监控模板，监控模板保存后，
基于监控模板创建监控只需要填写变量值即可，基于模板一次可以创建多个监控，因为变量值可以设置N对值，就可以生成N个监控。

**Comment by LittleShrimp1987** [comment]
> 1、如果事件发生的时间是21点到早上6点，非紧急告警可以只做记录，而非直接推送。
> 2、获取到告警消息后 支持告警的分组处理，比如 获取到service.name，发给相关的负责人

1. 计划保存监控时，可以设置风险等级，和允许报警发送的时间段
2. 计划增加服务管理功能，服务可以设置相关负责人，服务可以和监控关联，表示监控属于哪个服务，关联了服务的监控报警时，会同时给相关人发送报警

**Comment by wajika** [comment]
忘记回复你了，你这边先做出来看看效果把
