### ISSUE TITLE
监控列表中添加了告警规则，告警任务不能自动触发执行，手动“执行一次”可以触发

### ISSUE THREAD

**Issue by shaoyuwu** [AutohomeCorp/frostmourne#152]

**Comment by LittleShrimp1987** [comment]
看下日志有没有报错信息

**Comment by deasyful** [comment]
> 看下日志有没有报错信息

![image](https://github.com/AutohomeCorp/frostmourne/assets/37526424/8b2cff3e-8526-4131-93fe-826a091ca06e)
我也遇到同样的问题，日志里有这个报错

**Comment by yangruilang** [comment]
同样的问题，配置了钉钉报警，手动执行能够成功，但是无法自动执行，怎么解决？

**Comment by sanutey** [comment]
> > 看下日志有没有报错信息
> 
> ![image](https://github.com/AutohomeCorp/frostmourne/assets/37526424/8b2cff3e-8526-4131-93fe-826a091ca06e) 我也遇到同样的问题，日志里有这个报错

URI 地址没有以 http:// 或 https:// 协议开头

**Comment by sanutey** [comment]
> 同样的问题，配置了钉钉报警，手动执行能够成功，但是无法自动执行，怎么解决？

看看有没有错误日志
