### ISSUE TITLE
预警邮件主题乱码

### ISSUE THREAD

**Issue by chuqiao8250** [AutohomeCorp/frostmourne#154]
![image](https://github.com/AutohomeCorp/frostmourne/assets/17548772/8c9bea31-696c-4364-a6ee-1dfe3726c6f9)

怎么解决？

**Comment by LittleShrimp1987** [comment]
看下报警发送的说明文档

**Comment by LittleShrimp1987** [comment]
https://github.com/AutohomeCorp/frostmourne/blob/master/doc/wiki/ways.md
