### ISSUE TITLE
连接Microsoft LDAP异常

### ISSUE THREAD

**Issue by energy-blockchian** [AutohomeCorp/frostmourne#25]
ldap_enabled=true
spring_ldap_urls=192.168.1.2
spring_ldap_username=tech
spring_ldap_password=abc@123
spring_ldap_base=ou=技术部,dc=sh,dc=energy-blockchain,dc=com
spring_ldap_auth_searchFilter=sAMAccountName={0}

"2020-11-30T10:53:56.281+08:00"	"ERROR"	"com.autohome.frostmourne.monitor.service.account.impl.LdapAuthService"	"38"	"org.springframework.ldap.UncategorizedLdapException"	"Uncategorized exception occured during LDAP processing; nested exception is javax.naming.NamingException: Cannot parse url: 192.168.1.2/ou=æ%C2%8A%C2%80æ%C2%9C¯é%C2%83¨,dc=sh,dc=energy-blockchain,dc=com [Root exception is java.net.MalformedURLException: Invalid URI: 192.168.1.2/ou=æ%C2%8A%C2%80æ%C2%9C¯é%C2%83¨,dc=sh,dc=energy-blockchain,dc=com]"	"error when ldap authenticate user: bin.sun"	"com.autohome.frostmourne.monitor.service.account.impl.LdapAuthService"	"validate"	"-"	"-"	"tech"	"frostmourne"	"frostmourne.monitor"	"-"	"25"	"http-nio-10054-exec-3"	"-"	"192.168.1.166"	"-"	"-"	"-"	"-"	"org.springframework.ldap.UncategorizedLdapException: Uncategorized exception occured during LDAP processing; nested exception is javax.naming.NamingException: Cannot parse url: 192.168.1.2/ou=æ%C2%8A%C2%80æ%C2%9C¯é%C2%83¨,dc=sh,dc=energy-blockchain,dc=com [Root exception is java.net.MalformedURLException: Invalid URI: 192.168.1.2/ou=æ%C2%8A%C2%80æ%C2%9C¯é%C2%83¨,dc=sh,dc=energy-blockchain,dc=com]

不清LDAP这块的配置该如何配置的，报了一个如图的错误，用的是微软的AD Server，配置如图，Urls和base这两块配置找了下没有可供参考的。

**Comment by LittleShrimp1987** [comment]
spring_ldap_urls服务地址格式不正确没有协议和端口

**Comment by LittleShrimp1987** [comment]
比如： ldap://192.168.1.2:389

**Comment by energy-blockchian** [comment]
### ldap setttings
ldap_enabled=true
spring_ldap_urls=ldap://192.168.1.2:389
spring_ldap_username=tech
spring_ldap_password=abc@123
spring_ldap_base=ou=技术部,dc=sh,dc=energy-blockchain,dc=com
spring_ldap_auth_searchFilter=sAMAccountName={0}
#spring_ldap_auth_searchFilter=uid={0}

"2020-11-30T17:22:05.225+08:00" "ERROR" "com.autohome.frostmourne.monitor.service.account.impl.LdapAuthService" "38"    "org.springframework.ldap.AuthenticationException"      "[LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903C5, comment: AcceptSecurityContext error, data 52e, v2580^@]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903C5, comment: AcceptSecurityContext error, data 52e, v2580^@]"        "error when ldap authenticate user: bin.sun"    "com.autohome.frostmourne.monitor.service.account.impl.LdapAuthService" "validate"      "-"     "-"     "tech"  "frostmourne"   "frostmourne.monitor"   "-"     "29"    "http-nio-10054-exec-4" "-"     "192.168.1.166" "-"     "-"     "-"     "-"     "org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903C5, comment: AcceptSecurityContext error, data 52e, v2580^@]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903C5, comment: AcceptSecurityContext error, data 52e, v2580^@]

这个base的写法是对的吗？

**Comment by LittleShrimp1987** [comment]
> ### ldap setttings
> ldap_enabled=true
> spring_ldap_urls=ldap://192.168.1.2:389
> spring_ldap_username=tech
> spring_ldap_password=abc@123
> spring_ldap_base=ou=技术部,dc=sh,dc=energy-blockchain,dc=com
> spring_ldap_auth_searchFilter=sAMAccountName={0}
> #spring_ldap_auth_searchFilter=uid={0}
> 
> "2020-11-30T17:22:05.225+08:00" "ERROR" "com.autohome.frostmourne.monitor.service.account.impl.LdapAuthService" "38" "org.springframework.ldap.AuthenticationException" "[LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903C5, comment: AcceptSecurityContext error, data 52e, v2580^@]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903C5, comment: AcceptSecurityContext error, data 52e, v2580^@]" "error when ldap authenticate user: bin.sun" "com.autohome.frostmourne.monitor.service.account.impl.LdapAuthService" "validate" "-" "-" "tech" "frostmourne" "frostmourne.monitor" "-" "29" "http-nio-10054-exec-4" "-" "192.168.1.166" "-" "-" "-" "-" "org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903C5, comment: AcceptSecurityContext error, data 52e, v2580^@]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903C5, comment: AcceptSecurityContext error, data 52e, v2580^@]
> 
> 这个base的写法是对的吗？

这个只能你自己确定了，我没办法知道

**Comment by LittleShrimp1987** [comment]
你们ldap谁维护的呢？问下维护人员

**Comment by energy-blockchian** [comment]
"label":"LDAP","host":"192.168.1.2","port":389,"uid":"sAMAccountName","bind_dn":"CN=administrator,CN=Users,DC=sh,DC=energy-blockchain,DC=com","password":"00000","encryption":"plain","active_directory":true,"allow_username_or_email_login":false,"block_auto_created_users":false,"base":"ou=技术部,dc=sh,dc=energy-blockchain,dc=com","user_filter":""


我在维护，这个是我们gitlab上的配置，我理解的base就是"ou=技术部,dc=sh,dc=energy-blockchain,dc=com"

**Comment by LittleShrimp1987** [comment]
username配置加上邮箱后缀试试吧

**Comment by energy-blockchian** [comment]
试过的，不行。

Caused by: javax.naming.NameNotFoundException: [LDAP: error code 32 - 0000208D: NameErr: DSID-03100238, problem 2001 (NO_OBJECT), data 0, best match of:
        'DC=sh,DC=energy-blockchain,DC=com'
^@]; remaining name '/'
        at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3179)
        at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3100)
        at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2891)
        at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1846)
        at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1769)
        at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:392)
        at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:358)
        at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:276)
        at org.springframework.ldap.core.LdapTemplate$3.executeSearch(LdapTemplate.java:303)
        at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:363)
        ... 58 more
"^M
"2020-11-30T20:13:27.286+08:00" "ERROR" "com.autohome.frostmourne.monitor.config.GlobalControllerAdvice"        "24"    "com.autohome.frostmourne.core.contract.ProtocolException"      "用户名或密码错误"      "global catch exception"        "com.autohome.frostmourne.monitor.config.GlobalControllerAdvice"        "handleProtocolException"       "-"     "-"     "tech"  "frostmourne"   "frostmourne.monitor"   "-"     "28"    "http-nio-10054-exec-6" "-"     "192.168.1.166" "-"     "-"     "-"     "-"     "com.autohome.frostmourne.core.contract.ProtocolException: 用户名或密码错误

**Comment by LittleShrimp1987** [comment]
ldap错误，需要自己排查一下了
