### ISSUE TITLE
希望支持按指定字段进行分组Count功能

### ISSUE THREAD

**Issue by likaijames** [AutohomeCorp/frostmourne#29]
现在监控的数据配置里，聚合类型指定为count时，就无法再指定聚合字段。（指定其他聚合类型时，就可以指定聚合字段）。
无法满足一次监控多个动态桶的聚合指标是否异常的需求。

希望修改一下，允许按指定聚合字段进行分组count，并进行指标判断和告警。

**Comment by LittleShrimp1987** [comment]
这种建议每个桶拆成一个监控，而不是用一个监控来监控所有桶

**Comment by likaijames** [comment]
非常感谢你的回复。不过我现在遇到的问题是：桶是动态的，不确定的。因此没法针对固定的桶做监控。
比如我面对的场景：监控所有用户的某个系统的认证日志，在一定期间内某个用户的认证失败次数达到某个阈值，就进行告警。
针对上面这个场景，不知道你有什么好的建议方案么？期待你的回复，谢谢！

**Comment by LittleShrimp1987** [comment]
用http监控试一下： https://github.com/AutohomeCorp/frostmourne/blob/master/doc/wiki/http-alarm.md  按user 做terms aggregation，取topN，用top1的value做为表达式判断条件： bucket[0].value > 3, 还可以用kibana做一个图表，以短链接的形式放到报警消息里，虽然爆出来是top1的，图表里可以看到更多详细的内容
