### ISSUE TITLE
提一条关于恢复告警的小建议

### ISSUE THREAD

**Issue by Jincysofun** [AutohomeCorp/frostmourne#31]
能否支持单独的查询项来确定告警是否恢复。因为有些服务的告警日志是重要且偶发的，服务日志可以定义相应的关键字来确定服务状态是否恢复。望采纳(●'◡'●)

**Comment by LittleShrimp1987** [comment]
如果不想要恢复通知 可以设置关闭

**Comment by LittleShrimp1987** [comment]
建议不要用一个任务监控多个服务 应该用一个任务监控一个服务，这样简单灵活。如果恢复也要设置动态语句条件 操作过于复杂 所以先不采纳您的建议了
