### ISSUE TITLE
frostmoure如何配置AWS_ES作为数据源

### ISSUE THREAD

**Issue by zxj1023** [AutohomeCorp/frostmourne#35]
java.lang.NumberFormatException: For input string: ""//vpc-oregon-elk-es.xxxxxxxxxxxxx.us-west-2.es.amazonaws.com"
1.配置ES数据源是否只能通过:地址+端口形式（127.0.0.1:91200），现在使用AWS_ES地址（服务地址：https//vpc-oregon-elk-es.xxxxxxxxxxxxx.us-west-2.es.amazonaws.com）配置数据源出现以上错误
2.使用地址+端口形式（vpc-oregon-elk-es.xxxxxxxxxxxxx.us-west-2.es.amazonaws.com:443）但由于AWS_ES服务现在原因出现400，AWS_ES服务不支持http请求请问如何
请教一下需要如何进行正确配置

**Comment by LittleShrimp1987** [comment]
现在还没有考虑https，这个我后面实现一下。但是es服务必须支持http请求，确定AWS_ES服务不支持http请求吗？

**Comment by LittleShrimp1987** [comment]
https支持，我周末实现一下

**Comment by zxj1023** [comment]
> https支持，我周末实现一下

感谢目前来看是不支持的直接400了，我现在是架了一台ng做了个反向代理，frostmoure直接访问ng是可以的

**Comment by LittleShrimp1987** [comment]
最新版本elasticsearch数据源增加https选项开关

**Comment by zxj1023** [comment]
> 最新版本elasticsearch数据源增加https选项开关



> 最新版本elasticsearch数据源增加https选项开关

![image](https://user-images.githubusercontent.com/32091024/111101100-2baf0600-8584-11eb-9661-217fe875d8c3.png)
![image](https://user-images.githubusercontent.com/32091024/111101206-6022c200-8584-11eb-9eca-701087802fa9.png)
勾选开关配置地址仍然无法查询数据，报错跟以前一样

**Comment by LittleShrimp1987** [comment]
报啥错，错误贴一下

**Comment by LittleShrimp1987** [comment]
服务地址不带scheme

**Comment by LittleShrimp1987** [comment]
服务地址这么写: vpc.oregionxxxx:${port}, 不要带scheme

**Comment by LittleShrimp1987** [comment]
ealsticsearch数据源已经支持https

**Comment by LittleShrimp1987** [comment]
具体设置方法看文档： https://github.com/AutohomeCorp/frostmourne/blob/master/doc/wiki/es.md
