### ISSUE TITLE
报警发送添加对用户组的支持并且可以自动发现供选取

### ISSUE THREAD

**Issue by fox2zz** [AutohomeCorp/frostmourne#4]
[简述你的问题]
希望能通过`所属团队`查看监控列表，报警发送支持用户组的形式。
对已存在的用户组，在报警发送界面可以支持自动发现供选取。

使用版本
[请提供你使用的frostmourne版本]
0.1-RELEASE

具体表现[截图可能会更好些,最好能截全]
GroupA 对应 UserA，UserB，UserC
通过选择GroupA即可发送至UserA，UserB，UserC

其他
用户组中的用户可能属于不同部门，需要灵活调整。

[注:] 完成后请关闭 issue

**Comment by LittleShrimp1987** [comment]
接收人配置除了可以配置单个接收人，再增加一个可选的接收组配置，应该就可以了

**Comment by LittleShrimp1987** [comment]
配置报警接收人时，用户名自动提示功能已经可用
