### ISSUE TITLE
Mysql的版本是8.0吗

### ISSUE THREAD

**Issue by TroubleJin** [AutohomeCorp/frostmourne#40]

**Comment by LittleShrimp1987** [comment]
我自己测试用的mysql5

**Comment by LittleShrimp1987** [comment]
是碰到啥问题吗？

**Comment by TroubleJin** [comment]
5.6还是5.7的哈。8的数据库有报错哈

**Comment by LittleShrimp1987** [comment]
具体报错信息贴一下

**Comment by LittleShrimp1987** [comment]
5.7

**Comment by TroubleJin** [comment]
使用Http收不到消息

**Comment by TroubleJin** [comment]
![Uploading image.png…]()

**Comment by TroubleJin** [comment]
"2021-04-23T19:44:46.129+08:00"	"WARN"	"com.autohome.frostmourne.monitor.service.core.execute.GenerateShortLinkService"	"55"	"-"	"-"	"error when generate short link. response: {""returncode"":0,""message"":""ok"",""result"":null}"	"com.autohome.frostmourne.monitor.service.core.execute.GenerateShortLinkService"	"generate"	"-"	"-"	"tech"	"frostmourne"	"frostmourne.monitor"	"-"	"210"	"http-nio-10054-exec-1"	"-"	"172.18.0.5"	"-"	"-"	"-"	"-"	"-"
"2021-04-23T19:45:19.222+08:00"	"WARN"	"com.autohome.frostmourne.monitor.service.core.execute.GenerateShortLinkService"	"55"	"-"	"-"	"error when generate short link. response: {""returncode"":0,""message"":""ok"",""result"":null}"	"com.autohome.frostmourne.monitor.service.core.execute.GenerateShortLinkService"	"generate"	"-"	"-"	"tech"	"frostmourne"	"frostmourne.monitor"	"-"	"266"	"Thread-190"	"-"	"172.18.0.5"	"-"	"-"	"-"	"-"	"-"
"2021-04-23T19:45:19.239+08:00"	"ERROR"	"com.autohome.frostmourne.monitor.service.core.alert.AlertService"	"58"	"-"	"-"	"no recipients, alarmId: 1"	"com.autohome.frostmourne.monitor.service.core.alert.AlertService"	"alert"	"-"	"-"	"tech"	"frostmourne"	"frostmourne.monitor"	"-"	"266"	"Thread-190
