### ISSUE TITLE
集群es存在告警通知是空的情况，3个es节点，2个副本

### ISSUE THREAD

**Issue by TroubleJin** [AutohomeCorp/frostmourne#43]
![image](https://user-images.githubusercontent.com/48788965/126738544-fdb2015a-ec3a-40dd-8e0e-86551a88b03f.png)

**Comment by TroubleJin** [comment]
"2021-07-23T12:47:06.693+08:00"	"ERROR"	"com.autohome.frostmourne.monitor.service.core.query.impl.ElasticsearchDataQuery"	"167"	"-"	"-"	"totalCount 2, but hits length is 0, query: status:500, start: 2021-07-23T12:46:06.042+08:00, end: 2021-07-23T12:47:06.042+08:00"	"com.autohome.frostmourne.monitor.service.core.query.impl.ElasticsearchDataQuery"	"queryElasticsearchMetricValue"	"-""-"	"tech"	"frostmourne"	"frostmourne.monitor"	"-"	"328"	"Thread-231"	"-"	"172.18.0.5"	"-"	"-"	"-"	"-"	"-"

**Comment by LittleShrimp1987** [comment]
会一直这样吗？还是偶尔会出这个问题

**Comment by TroubleJin** [comment]
偶尔，如果es连接的节点没有那个索引副本的话，数据会一直都是空的，但是会显示条数

**Comment by LittleShrimp1987** [comment]
问题收到，我们排查一下

**Comment by TroubleJin** [comment]
好的，多谢。

**Comment by TroubleJin** [comment]
有解决吗

**Comment by LittleShrimp1987** [comment]
> 有解决吗

已经更新了一版，增加了重试机制

**Comment by TroubleJin** [comment]
镜像有更新吗。

**Comment by LittleShrimp1987** [comment]
有，镜像已经更新

**Comment by TroubleJin** [comment]
用0.5的镜像还是0.4的哈

**Comment by LittleShrimp1987** [comment]
0.5

**Comment by LittleShrimp1987** [comment]
问题原因是为了兼容es版本，查数量和查日志明细分成两次查询，可能命中不同的分片，导致数量大于0，明细一条都没有。
