### ISSUE TITLE
通过HTTP监控告警出现unknown exception

### ISSUE THREAD

**Issue by zhangheng3** [AutohomeCorp/frostmourne#54]
我想通过监控prometheus http api 来触发告警, 在后台配置好监控地址后, 浏览数据正常.
{
"data": {
"resultType": "vector",
"result": [
{
"metric": {
"__name__": "kafka_cluster_partition_atminisr",
"instance": "localhost:9991",
"job": "ad-kafka",
"partition": "0",
"topic": "ad_station"
},
"value": [
1648002724.339,
"0"
]
}
]
},
"HTTP_STATUS": 200,
"EXPRESSION": "data.result[0].value[0] > 10",
"HTTP_COST": 2,
"status": "success"
}

然后在告警规则中判断表达式: data.result[0].value[0] > 10
最后保存的时候提示:  unknown exception

请问我有哪里写的有问题吗?

**Comment by zhangheng3** [comment]
错误日志信息: 
"2022-03-23T10:33:28.123+08:00"	"ERROR"	"com.autohome.frostmourne.monitor.service.admin.impl.AlarmAdminService"	"117"	"java.lang.NullPointerException"	"-"	"error when save alarm"	"com.autohome.frostmourne.monitor.service.admin.impl.AlarmAdminService"	"atomicSave"	"-"	"-"	"tech"	"frostmourne"	"frostmourne.monitor"	"-"	"205"	"http-nio-10054-exec-10"	"-"	"localhost"	"-"	"-"	"-"	"-"	"java.lang.NullPointerException
	at com.autohome.frostmourne.monitor.service.admin.impl.ScheduleService.toXxlJobInfo(ScheduleService.java:92)
	at com.autohome.frostmourne.monitor.service.admin.impl.ScheduleService.addJob(ScheduleService.java:31)
	at com.autohome.frostmourne.monitor.service.admin.impl.AlarmAdminService.saveJobSchedule(AlarmAdminService.java:449)

**Comment by zhangheng3** [comment]
用的是最新的0.4-RELEASE版本，发现只要选择http监控就会报错。 不管内容填写的是啥

**Comment by LittleShrimp1987** [comment]
看下xxl.job.executor.id这个配置了吗？

**Comment by LittleShrimp1987** [comment]
最好用最新的0.5

**Comment by zhangheng3** [comment]
更新版本了, 已经恢复. 多谢~~
