### ISSUE TITLE
未来的版本会把prometheus做成Datasource, 跟ES Influxdb clickhouse 一样吗?

### ISSUE THREAD

**Issue by zhangheng3** [AutohomeCorp/frostmourne#55]
未来的版本会把prometheus做成Datasource, 跟ES Influxdb clickhouse 一样吗?  添加告警直接写promeQL就行了.
目前HTTP的这种方式去告警prometheus 写规则还是比较麻烦.

**Comment by LittleShrimp1987** [comment]
是，在后续规划里确实有这部分计划

**Comment by LittleShrimp1987** [comment]
0.7版本已经支持
