### ISSUE TITLE
聚合类型为count时可以按字段吗

### ISSUE THREAD

**Issue by shenxf1205** [AutohomeCorp/frostmourne#56]
各位大佬好，目前的平台在聚合类型为count时可以按字段统计吗，如下：
nginx的5xx按域名字段来统计数量并告警，比如单个域名5xx达到10次就告警
目前的count是不区分域名，统计的都是所有值

**Comment by LittleShrimp1987** [comment]
数据分桶统计已经在后续规划中

**Comment by shenxf1205** [comment]
好的，谢谢，期待新版本的上线

**Comment by LittleShrimp1987** [comment]
0.6.2版本开始支持
