### ISSUE TITLE
建议增加k8s部署版本

### ISSUE THREAD

**Issue by JiuXiangZX** [AutohomeCorp/frostmourne#57]
大佬们，有计划增加k8s版本部署嘛

**Comment by LittleShrimp1987** [comment]
计划移除spi和xxl-job依赖，简化项目结构和部署之后，增加k8s部署的说明。其实那时候就是一个简单的java项目部署了，非常简单了。

**Comment by LittleShrimp1987** [comment]
readme已经增加k8s部署说明
