### ISSUE TITLE
用户问题

### ISSUE THREAD

**Issue by wisonzhu** [AutohomeCorp/frostmourne#6]
每次新增用户的时候需要重启spi服务，没法自助处理。

建议前期先增加用户管理功能方便用户自助维护，后期根据功能需要再对接第三方用户系统，比如sso，ldap之类的。

**Comment by LittleShrimp1987** [comment]
已经加入后续规划

**Comment by LittleShrimp1987** [comment]
已经增加了账号信息管理模块作为默认实现
