### ISSUE TITLE
查询数据的时候提示 unknown exception

### ISSUE THREAD

**Issue by q2444** [AutohomeCorp/frostmourne#61]
我现在数据源里添加了es库，同时增加了数据名。在数据查询时提示  unknown exception
![image](https://user-images.githubusercontent.com/91019613/162853012-19c940fc-1e33-428f-ab4b-e318219c1a1c.png)
![image](https://user-images.githubusercontent.com/91019613/162853051-3d3fff26-9b3a-43f6-999c-fd8ff0d0fc02.png)
![image](https://user-images.githubusercontent.com/91019613/162853074-c603164b-367d-4dca-8b39-0b708dc58209.png)

**Comment by LittleShrimp1987** [comment]
看看日志里有啥报错信息没有

**Comment by q2444** [comment]
发现是日期那里写的 timestamp ，应该写 @timestamp
