### ISSUE TITLE
我添加定时任务后，报错日志如图

### ISSUE THREAD

**Issue by q2444** [AutohomeCorp/frostmourne#72]
我把p12改成了本地证书，添加监控编辑时的报错是
![image](https://user-images.githubusercontent.com/91019613/164912502-81102d5f-a57e-4d78-a643-5dc2a2c16814.png)

自动执行定时任务时报错是
![image](https://user-images.githubusercontent.com/91019613/164912349-2aa59abe-725d-4156-8dfc-9530b5c951ed.png)

**Comment by LittleShrimp1987** [comment]
看看你frostmourne_monitor_address配置的是啥，需要配置绝对地址，比如： http://localhost:10054
