### ISSUE TITLE
数据查询页面不支持ES8

### ISSUE THREAD

**Issue by timebombxyz** [AutohomeCorp/frostmourne#73]
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=x_content_parse_exception, reason=[1:792] [date_histogram] unknown field [interval] did you mean [fixed_interval]?]

**Comment by LittleShrimp1987** [comment]
正在考虑支持elasticsearch 6, 7, 8三个版本

**Comment by LittleShrimp1987** [comment]
最新版本已经增加对es8的支持
