### ISSUE TITLE
规划中哪些是你比较需要的功能可以在这里反馈

### ISSUE THREAD

**Issue by LittleShrimp1987** [AutohomeCorp/frostmourne#91]
规划中哪些是你比较需要的功能可以在这里反馈

**Comment by onecer** [comment]
判断规则支持函数？
表达式感觉有点局限性。
有这么一个场景，我用prometheus数据源，查出一组的数据（不固定长度的）。我想判断这一组只要其中一个满足条件就可以告警。
用表达式不知道怎么写好。
如果支持函数，那我可以遍历该数组，然后挨个对比，如果一发现满足条件，就返回true，其它情况返回false。

**Comment by Songxwn** [comment]
1、可以加入排班制度，不在班次的人不会被发送告警消息。 我们公司是白夜休休的值班制度，可以设置不值班的时间不会被企业微信机器人@，不被发送邮件等。。
2、希望相关的技术文档更多更详细一些。
